[tool.poetry]
name = "fast-alchemy"
version = "0.2.0"
description = "Framework for Orthoresa"
authors = ["Clement_Hue <clementhue@hotmail.fr>"]

[tool.poetry.dependencies]
python = ">=3.8"
fastapi = "^0.79.0"
SQLAlchemy = "^1.4.40"
factory-boy = "^3.2.1"
alembic = "^1.8.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.8.2"
pytest-asyncio = "^0.19.0"

[tool.pytest.ini_options]
addopts = "-s  --color=yes"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
